server:
  shutdown: graceful
spring:
  servlet:
    multipart:
      max-file-size: 1MB
  #  session:
  #    store-type: redis
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${github-client-id}
            client-secret: ${github-client-secret}
            redirect-uri: ${redirect-uri}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    aws:
      s3:
        endpoint: ${npc-end-point}
        region: ${ncp-region}
      credentials:
        access-key: ${npc-access-key}
        secret-key: ${npc-secret-key}

ncp:
  region: ${ncp-region}
  end-point: ${npc-end-point}
  access-key: ${npc-access-key}
  secret-key: ${npc-secret-key}
  bucket-name: ${npc-bucket-name}
springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"
