server:
  servlet:
    session:
      timeout: 60m
      cookie:
        # 도메인 적용 & SSL 적용 안된 상태
        #domain: celog.com
        #secure: true
        max-age: 60m
        http-only: true

spring:
  # docker compose support (로컬 환경을 구성하기 위한 목적이므로)
  docker:
    compose:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${celog-mysql-url}
    username: ${celog-mysql-username}
    password: ${celog-mysql-password}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: ${celog-jpa-ddl-auto}
