name: Test Environment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Create .env file
        run: |
          jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$SECRETS_CONTEXT" > .env
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets.ENV_CONFIG) }}

      - name: Set environment variables
        env:
          ENV_FILE: .env
        run: |
          # .env 파일에서 환경 변수 읽어들이기
          set -a
          . $ENV_FILE
          set +a
          
          # 설정된 환경 변수 확인
          echo "Environment variables set:"
          env
