name: Test Environment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Load environment variables
        id: load_env
        run: |
          # GitHub Secrets의 env.json 파일을 읽어들이기
          echo ${{ secrets.ENV_CONFIG }} > env.json
          
          # env.json 파일에서 key-value 쌍 추출하기
          for i in $(jq -r 'to_entries | map("\(.key)=\(.value)") | .[]' env.json); do
            echo "$i"
          done

      - name: Set environment variables
        env:
          ${{ toJson(steps.load_env.outputs) }}
        run: |
          # 추출한 환경 변수를 실제로 설정하기
          echo "Environment variables set:"
          env
        
