name: Test Environment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Export variables from secret
        run: |
          ENV_JSON='${{ secrets.ENV_CONFIG }}'
          echo "$ENV_JSON" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV

      - name: echo version
        run: echo "$"

      - name: Print Env
        run: |
          
          # 설정된 환경 변수 확인
          echo "Environment variables set:"
          env
